# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='账号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('display_name', models.CharField(max_length=150, verbose_name='姓名')),
                ('role', models.CharField(choices=[('member', '普通成员'), ('admin', '业务管理员'), ('super_admin', '超级管理员')], default='member', max_length=20, verbose_name='角色')),
                ('account_status', models.CharField(choices=[('invited', '已邀请'), ('pending_approval', '待审批'), ('active', '已激活'), ('disabled', '已禁用')], default='invited', max_length=20, verbose_name='账号状态')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='TOTP 已启用')),
                ('totp_required', models.BooleanField(default=False, verbose_name='强制 TOTP')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='上次登录')),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='密码修改时间')),
                ('activation_token', models.CharField(blank=True, default='', max_length=64)),
                ('activation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Django Admin 访问')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=150, verbose_name='姓名')),
                ('username', models.CharField(max_length=150, verbose_name='申请账号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('department_name', models.CharField(max_length=200, verbose_name='部门')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审批备注')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '注册申请',
                'verbose_name_plural': '注册申请',
                'db_table': 'registration_requests',
            },
        ),
        migrations.CreateModel(
            name='SessionRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('invalidate_before', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_revocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会话撤销',
                'verbose_name_plural': '会话撤销',
                'db_table': 'session_revocations',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status', 'role'], name='users_account_9384d4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'account_status'], name='users_departm_50f14a_idx'),
        ),
    ]
