# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '个人计划',
                'verbose_name_plural': '个人计划',
                'db_table': 'private_plans',
            },
        ),
        migrations.CreateModel(
            name='PrivatePlanAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='attachments.attachment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_attachments', to='private_plans.privateplan')),
            ],
            options={
                'verbose_name': '个人计划附件',
                'verbose_name_plural': '个人计划附件',
                'db_table': 'private_plan_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='privateplan',
            index=models.Index(fields=['owner', 'status', 'due_date'], name='private_pla_owner_i_69f47b_idx'),
        ),
    ]
