# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', '已计划'), ('in_progress', '进行中'), ('finished', '已结束')], default='planned', max_length=20, verbose_name='状态')),
                ('member_order_json', models.JSONField(default=list, verbose_name='成员顺序')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='会议备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='reporting.reportingperiod')),
            ],
            options={
                'verbose_name': '组会',
                'verbose_name_plural': '组会',
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='MeetingReportState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussed', models.BooleanField(default=False, verbose_name='已讨论')),
                ('discussed_at', models.DateTimeField(blank=True, null=True, verbose_name='讨论时间')),
                ('note', models.TextField(blank=True, default='', verbose_name='会议备注')),
                ('discussed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_marks', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_states', to='meetings.meeting')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_states', to='reporting.weeklyreport')),
            ],
            options={
                'verbose_name': '讨论状态',
                'verbose_name_plural': '讨论状态',
                'db_table': 'meeting_report_states',
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='行动项')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('done', '已完成'), ('cancelled', '已取消')], default='open', max_length=20, verbose_name='状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='解决备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL)),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='reporting.weeklyreport')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting')),
            ],
            options={
                'verbose_name': '行动项',
                'verbose_name_plural': '行动项',
                'db_table': 'action_items',
                'indexes': [models.Index(fields=['owner', 'due_date', 'status'], name='action_item_owner_i_d59f80_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0, verbose_name='展示顺序')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='meetings.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_snapshots', to=settings.AUTH_USER_MODEL)),
                ('report_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_snapshots', to='reporting.weeklyreportrevision')),
            ],
            options={
                'verbose_name': '组会周报快照',
                'verbose_name_plural': '组会周报快照',
                'db_table': 'meeting_report_snapshots',
                'unique_together': {('meeting', 'member')},
            },
        ),
    ]
