# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('achievement', '完成事项'), ('risk', '风险'), ('blocker', '阻塞'), ('coordination', '待协调'), ('next_plan', '下周计划'), ('meeting_topic', '建议组会讨论')], max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('project', models.CharField(blank=True, default='', max_length=300, verbose_name='项目')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('human_status', models.CharField(default='pending', max_length=20, verbose_name='人工确认状态')),
                ('human_revision_comment', models.TextField(blank=True, default='', verbose_name='人工修订说明')),
                ('original_ai_output', models.JSONField(default=dict, verbose_name='原始 AI 条目')),
            ],
            options={
                'verbose_name': '分析条目',
                'verbose_name_plural': '分析条目',
                'db_table': 'analysis_items',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=200, verbose_name='模型标识')),
                ('prompt_version', models.CharField(max_length=50, verbose_name='Prompt 版本')),
                ('input_text_hash', models.CharField(max_length=64, verbose_name='输入文本哈希')),
                ('output_json', models.JSONField(verbose_name='原始 AI 输出')),
                ('schema_version', models.CharField(max_length=50, verbose_name='Schema 版本')),
                ('status', models.CharField(default='completed', max_length=30, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Token 用量')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '分析运行',
                'verbose_name_plural': '分析运行',
                'db_table': 'analysis_runs',
            },
        ),
        migrations.CreateModel(
            name='TeamSummarySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_json', models.JSONField(verbose_name='总表数据')),
                ('item_count', models.IntegerField(default=0, verbose_name='条目数')),
            ],
            options={
                'verbose_name': '团队总表',
                'verbose_name_plural': '团队总表',
                'db_table': 'team_summary_snapshots',
            },
        ),
        migrations.CreateModel(
            name='AnalysisHumanRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_data', models.JSONField(verbose_name='修订前数据')),
                ('new_data', models.JSONField(verbose_name='修订后数据')),
                ('revised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_revisions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_revisions', to='analysis.analysisitem')),
            ],
            options={
                'verbose_name': '人工修订',
                'verbose_name_plural': '人工修订',
                'db_table': 'analysis_human_revisions',
            },
        ),
        migrations.CreateModel(
            name='AnalysisItemSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('report_field', '周报字段'), ('attachment', '附件')], max_length=20, verbose_name='来源类型')),
                ('source_id', models.CharField(max_length=255, verbose_name='来源 ID')),
                ('page', models.IntegerField(default=1, verbose_name='页码')),
                ('quote_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='引用哈希')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='analysis.analysisitem')),
            ],
            options={
                'verbose_name': '来源追溯',
                'verbose_name_plural': '来源追溯',
                'db_table': 'analysis_item_sources',
            },
        ),
    ]
