# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='reporting.weeklyreportrevision'),
        ),
        migrations.AddField(
            model_name='analysisitem',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analysis.analysisrun'),
        ),
        migrations.AddField(
            model_name='teamsummarysnapshot',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamsummarysnapshot',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_summaries', to='reporting.reportingperiod'),
        ),
        migrations.AddIndex(
            model_name='analysisitem',
            index=models.Index(fields=['analysis_run', 'item_type'], name='analysis_it_analysi_33d8a9_idx'),
        ),
    ]
