# Generated by Django 6.0.7 on 2026-07-19 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='说明')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'system_settings',
            },
        ),
    ]
