# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_year', models.IntegerField(verbose_name='ISO 年份')),
                ('iso_week', models.IntegerField(verbose_name='ISO 周数')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('deadline', models.DateTimeField(verbose_name='提交截止时间')),
                ('status', models.CharField(choices=[('open', '开放提交'), ('closed', '已截止'), ('archived', '已归档')], default='open', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '周报周期',
                'verbose_name_plural': '周报周期',
                'db_table': 'reporting_periods',
                'ordering': ['-iso_year', '-iso_week'],
                'unique_together': {('iso_year', 'iso_week')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_content_json', models.JSONField(default=dict, verbose_name='草稿内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('resubmitted', '补交'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('optimistic_version', models.IntegerField(default=0, verbose_name='乐观锁版本')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reporting.reportingperiod')),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
                'db_table': 'weekly_reports',
            },
        ),
        migrations.CreateModel(
            name='AdminReportNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='备注内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='reporting.weeklyreport')),
            ],
            options={
                'verbose_name': '管理员备注',
                'verbose_name_plural': '管理员备注',
                'db_table': 'admin_report_notes',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_no', models.IntegerField(verbose_name='修订编号')),
                ('structured_content_json', models.JSONField(verbose_name='结构化内容快照')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('content_sha256', models.CharField(max_length=64, verbose_name='内容哈希')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='提交/修改原因')),
                ('confirmed_pdf_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_for_revisions', to='attachments.attachment', verbose_name='成员确认的 PDF')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='reporting.weeklyreport')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '周报修订版',
                'verbose_name_plural': '周报修订版',
                'db_table': 'weekly_report_revisions',
                'ordering': ['-revision_no'],
                'unique_together': {('report', 'revision_no')},
            },
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reporting.weeklyreportrevision'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['status', 'reporting_period'], name='weekly_repo_status_38c2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['owner', 'reporting_period'], name='weekly_repo_owner_i_5daee7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('owner', 'reporting_period')},
        ),
    ]
