# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentCompatibilityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_mime', models.CharField(max_length=255, verbose_name='实际 MIME')),
                ('extension_matches_mime', models.BooleanField(default=True, verbose_name='扩展名与 MIME 一致')),
                ('format_family', models.CharField(blank=True, default='', max_length=50, verbose_name='格式家族')),
                ('legacy_format', models.BooleanField(default=False, verbose_name='旧版格式')),
                ('macro_enabled', models.BooleanField(default=False, verbose_name='含宏')),
                ('encrypted', models.BooleanField(default=False, verbose_name='已加密')),
                ('external_links', models.BooleanField(default=False, verbose_name='含外部链接')),
                ('declared_fonts', models.JSONField(default=list, verbose_name='声明字体')),
                ('font_matches', models.JSONField(default=dict, verbose_name='字体匹配结果')),
                ('missing_or_substituted_fonts', models.JSONField(default=list, verbose_name='缺失/替换字体')),
                ('embedded_objects', models.JSONField(default=list, verbose_name='嵌入对象')),
                ('preview_level', models.CharField(default='normal', max_length=20, verbose_name='预览等级')),
                ('warnings', models.JSONField(default=list, verbose_name='警告列表')),
            ],
            options={
                'verbose_name': '兼容性报告',
                'verbose_name_plural': '兼容性报告',
                'db_table': 'attachment_compatibility_reports',
            },
        ),
        migrations.CreateModel(
            name='AttachmentExtractedText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='抽取文本')),
                ('completeness', models.CharField(default='full', max_length=20, verbose_name='完整程度')),
                ('extractor_name', models.CharField(max_length=100, verbose_name='抽取器名称')),
                ('warnings', models.JSONField(default=list, verbose_name='警告')),
            ],
            options={
                'verbose_name': '抽取文本',
                'verbose_name_plural': '抽取文本',
                'db_table': 'attachment_extracted_texts',
            },
        ),
        migrations.CreateModel(
            name='AttachmentPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_object_key', models.CharField(max_length=500, verbose_name='预览对象键')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='源文件 SHA-256')),
                ('converter_name', models.CharField(max_length=100, verbose_name='转换器名称')),
                ('converter_version', models.CharField(max_length=100, verbose_name='转换器版本')),
                ('converter_image_digest', models.CharField(max_length=100, verbose_name='转换器镜像 digest')),
                ('font_bundle_version', models.CharField(blank=True, default='', max_length=100, verbose_name='字体包版本')),
                ('output_sha256', models.CharField(max_length=64, verbose_name='输出 SHA-256')),
                ('page_count', models.IntegerField(default=0, verbose_name='页数')),
                ('status', models.CharField(max_length=30, verbose_name='预览状态')),
                ('warnings_json', models.JSONField(default=dict, verbose_name='警告')),
            ],
            options={
                'verbose_name': '预览记录',
                'verbose_name_plural': '预览记录',
                'db_table': 'attachment_previews',
            },
        ),
        migrations.CreateModel(
            name='AttachmentProcessingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=30, verbose_name='旧状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='新状态')),
                ('task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Celery 任务 ID')),
                ('error_code', models.CharField(blank=True, default='', max_length=100, verbose_name='错误代码')),
                ('user_message', models.CharField(blank=True, default='', max_length=500, verbose_name='用户可读消息')),
                ('tech_diagnostic', models.JSONField(default=dict, verbose_name='技术诊断')),
                ('processor_version', models.CharField(blank=True, default='', max_length=100, verbose_name='处理组件版本')),
            ],
            options={
                'verbose_name': '处理事件',
                'verbose_name_plural': '处理事件',
                'db_table': 'attachment_processing_events',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=500, verbose_name='原始文件名')),
                ('safe_filename', models.CharField(max_length=500, verbose_name='安全文件名')),
                ('detected_mime', models.CharField(max_length=255, verbose_name='检测的 MIME')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='原件 SHA-256')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('original_object_key', models.CharField(blank=True, default='', max_length=500, verbose_name='原件对象键')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('quarantined', '已隔离'), ('scanning', '扫描中'), ('rejected', '已拒绝'), ('stored', '已存储'), ('compatibility_check', '兼容性检测中'), ('converting', '转换中'), ('preview_ready', '预览已生成'), ('preview_warning', '预览有警告'), ('user_confirmed', '成员已确认'), ('extracting', '文本抽取中'), ('analyzing', 'AI 分析中'), ('ready', '就绪'), ('ready_with_warning', '就绪（有警告）'), ('failed', '失败'), ('password_protected', '有密码保护'), ('unsupported', '不支持')], default='uploading', max_length=30, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('author_pdf_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_pdfs', to='attachments.attachment')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'attachments',
            },
        ),
    ]
