# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('private_plans', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='private_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='private_plans.privateplan'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reporting.weeklyreport'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachmentcompatibilityreport',
            name='attachment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_report', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='attachmentextractedtext',
            name='attachment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_text', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='attachmentpreview',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='attachmentprocessingevent',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_events', to='attachments.attachment'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['report', 'status'], name='attachments_report__c8f328_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['source_sha256'], name='attachments_source__100e44_idx'),
        ),
    ]
