# Generated by Django 6.0.7 on 2026-07-19 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='事件 ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', '登录成功'), ('LOGIN_FAILURE', '登录失败'), ('USER_CREATED', '创建用户'), ('USER_DISABLED', '禁用用户'), ('USER_ENABLED', '恢复用户'), ('ROLE_CHANGED', '角色变更'), ('PASSWORD_RESET', '密码重置'), ('REPORT_SUBMITTED', '周报提交'), ('REPORT_RESUBMITTED', '周报补交'), ('REPORT_VIEWED_BY_ADMIN', '管理员查看周报'), ('ATTACHMENT_UPLOADED', '附件上传'), ('ATTACHMENT_DOWNLOADED', '附件下载'), ('ATTACHMENT_REJECTED', '附件拒绝'), ('PREVIEW_RETRIED', '预览重试'), ('AI_REGENERATED', 'AI 重新生成'), ('AI_ITEM_EDITED', 'AI 条目人工修改'), ('MEETING_STARTED', '组会开始'), ('REPORT_MARKED_DISCUSSED', '标记已讨论'), ('EXPORT_CREATED', '导出创建'), ('EXPORT_DOWNLOADED', '导出下载'), ('SYSTEM_SETTING_CHANGED', '系统配置变更'), ('EMERGENCY_ACCOUNT_ENABLED', '应急账号启用')], max_length=50, verbose_name='事件类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作人 IP')),
                ('actor_user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent 摘要')),
                ('target_type', models.CharField(blank=True, default='', max_length=100, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, default='', max_length=255, verbose_name='目标 ID')),
                ('result', models.CharField(default='success', max_length=20, verbose_name='结果')),
                ('summary', models.TextField(blank=True, default='', verbose_name='变更摘要')),
                ('risk_level', models.CharField(default='low', max_length=20, verbose_name='风险级别')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='请求 ID')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计事件',
                'verbose_name_plural': '审计事件',
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'event_type'], name='audit_event_created_7d08ef_idx'), models.Index(fields=['actor', 'created_at'], name='audit_event_actor_i_e566c4_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_event_target__4ee5b6_idx')],
            },
        ),
    ]
